spring.application.name=document-qna-assistant
spring.config.import=optional:file:.env[.properties]


# =====================================================
# AI
# =====================================================

spring.ai.model.chat=google-genai
spring.ai.model.embedding=google-genai

# Google GenAI Settings
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY:${GOOGLE_API_KEY:}}
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.embedding.text.model=text-embedding-004

# =====================================================
# POSTGRESQL
# =====================================================

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# =====================================================
# FLYWAY
# =====================================================

spring.flyway.enabled=true

spring.ai.vectorstore.type=pgvector

# =====================================================
# MULTIPART UPLOAD & SYSTEM PROPERTIES
# =====================================================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.threads.virtual.enabled=true